version: "3"
services:
    solana-setup:    
        build: .
        image: solana-setup
        container_name: solana-setup
        restart: on-failure
        volumes:
            - ../solana-project:/home/ubuntu/solana-project
        ports:
            - "22:22"
            - "8899:8899"
            - "8900:8900"
            - "3000:3000"
#        network_mode: "host"
