[package]
name = "todo_smart_contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "2.2.1"

[dev-dependencies]
solana-program-test = "2.2.7"
solana-sdk = "2.2.2"

[lib]
crate-type = ["cdylib", "lib"]
#name = "todo_smart_contracts"